name: giveandtake
description: 21-1 MAD Team Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  firebase_core : ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_auth: ^1.2.0
  firebase_storage: ^8.1.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.3
  provider: ^5.0.0
  cupertino_icons: ^1.0.3
  image_picker: ^0.7.5+2
=======
  cloud_firestore: ^2.2.0
  firebase_auth: ^1.2.0
  firebase_storage: ^8.0.5
  google_fonts: ^2.0.0
  google_sign_in: ^5.0.3
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.7.4
>>>>>>> 64486a4df0fb9ad6428d8f6d2488fcf60ac660ef


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/hgu.png
    - assets/logo.png
<<<<<<< HEAD
=======

>>>>>>> 64486a4df0fb9ad6428d8f6d2488fcf60ac660ef
