name: giveandtake
description: 21-1 MAD Team Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core : ^1.7.0
  cloud_firestore: ^2.2.0
  firebase_auth: ^3.0.1
  geolocator: ^7.0.3
  firebase_storage: ^10.0.5
  google_fonts: ^2.0.0
  google_sign_in: ^5.0.3
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+3
  url_launcher: ^6.0.6
  fl_chart: ^0.36.1 # 새로운 api 사용(1) flutter chart
  google_maps_flutter: ^2.0.6 # 새로운 api 사용 (3) google maps flutter
  http: ^0.13.1
  json_serializable: ^4.1.0
  shared_preferences: 2.0.6 #added
  fluttertoast: ^8.0.8 #added
  firebase_messaging: ^10.0.5 #added
  flutter_local_notifications: ^9.0.1 #added by 찬식
  photo_view: ^0.12.0 #added
  intl: ^0.17.0 #added
  carousel_slider: ^4.0.0 #added 예은
  flutter_screenutil: ^5.0.0+2 #added by 찬식
  flutter_speed_dial: ^4.5.0 # JM
  flutter_cache_manager: ^3.1.2 # JM
  cached_network_image: ^3.1.0 # JM


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/hgu.png
    - assets/logo.png
    - assets/userDefault.png
    - assets/userDefaultImage.png
    - assets/defaultPhoto.png
    - assets/sample.jpg
    - images/img_not_available.jpeg
    - images/mimi1.gif
    - images/mimi2.gif
    - images/mimi3.gif
    - images/mimi4.gif
    - images/mimi5.gif
    - images/mimi6.gif
    - images/mimi7.gif
    - images/mimi8.gif
    - images/mimi9.gif
    - assets/desktop.png
    - assets/grow.png
    - assets/idea.png
    - assets/idea.png
    - assets/mobile.png
    - assets/social.png


  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

    - family: NanumBarunGothic
      fonts:
        - asset: fonts/NanumBarunGothic.ttf

    - family: NanumSquareRoundR
      fonts:
        - asset: fonts/NanumSquareRoundR.ttf

    - family: Roboto_Bold
      fonts:
        - asset: fonts/Roboto-Bold.ttf